[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ERGM = "d623cd87-b018-4e2a-bf53-b77ebcdc9da2"
ERGMCount = "7556d106-17e3-4d5c-b2ff-836722c37052"
Network = "027a387e-e55f-4537-a155-5037e5a23bdb"

[sources]
ERGMCount = {path = ".."}
ERGM = {url = "https://github.com/statistical-network-analysis-with-Julia/ERGM.jl.git"}
Network = {url = "https://github.com/statistical-network-analysis-with-Julia/Network.jl.git"}

[compat]
Documenter = "1"
